import { useEffect, useMemo, useState } from 'react';
import { BookOpen } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';
import { Card, PageHeader, LoadingState, EmptyState, KpiCard, SectionTitle, SearchInput, Badge } from '../components/ui';
import { getAllLessonPlans, getLessonPlansByTeacher } from '../services/monitorData';
import type { LessonPlanStats } from '@/types/admin';
import { format } from 'date-fns';

const MonitorLessonPlans = () => {
  const [loading, setLoading] = useState(true);
  const [plans, setPlans] = useState<LessonPlanStats[]>([]);
  const [byTeacher, setByTeacher] = useState<{ teacherId: string; teacherName: string; lessonPlanCount: number }[]>([]);
  const [search, setSearch] = useState('');

  useEffect(() => {
    (async () => {
      try {
        const [p, t] = await Promise.all([getAllLessonPlans(), getLessonPlansByTeacher()]);
        setPlans(p);
        setByTeacher(t);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const byGrade = useMemo(() => {
    const m = new Map<string, number>();
    plans.forEach((p) => m.set(p.grade_level || 'Unknown', (m.get(p.grade_level || 'Unknown') ?? 0) + 1));
    return Array.from(m.entries()).map(([grade, count]) => ({ grade, count })).sort((a, b) => b.count - a.count);
  }, [plans]);

  const topTeachers = useMemo(
    () => byTeacher.filter((t) => t.lessonPlanCount > 0).sort((a, b) => b.lessonPlanCount - a.lessonPlanCount).slice(0, 10),
    [byTeacher]
  );

  const filtered = useMemo(() => {
    const t = search.trim().toLowerCase();
    if (!t) return plans;
    return plans.filter(
      (p) =>
        (p.title || '').toLowerCase().includes(t) ||
        (p.teacher_name || '').toLowerCase().includes(t) ||
        (p.subject || '').toLowerCase().includes(t) ||
        (p.grade_level || '').toLowerCase().includes(t)
    );
  }, [plans, search]);

  if (loading)
    return (
      <>
        <PageHeader title="Lesson plans" icon={BookOpen} subtitle="Every lesson plan generated by teachers." />
        <LoadingState />
      </>
    );

  return (
    <>
      <PageHeader title="Lesson plans" icon={BookOpen} subtitle="Every AI-generated lesson plan, the teachers who created them, and the grade-level distribution." />

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <KpiCard label="Total plans" value={plans.length} tone="violet" />
        <KpiCard label="Distinct teachers" value={new Set(plans.map((p) => p.teacher_id)).size} tone="cyan" />
        <KpiCard label="Distinct grade levels" value={new Set(plans.map((p) => p.grade_level).filter(Boolean)).size} tone="amber" />
        <KpiCard label="This week" value={plans.filter((p) => new Date(p.created_at).getTime() > Date.now() - 7 * 86400000).length} tone="emerald" />
      </div>

      <div className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-2">
        <Card>
          <SectionTitle title="Lesson plans by grade level" />
          <div className="h-72 px-2 pb-3">
            {byGrade.length === 0 ? <EmptyState title="No plans yet" /> : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={byGrade}>
                  <CartesianGrid stroke="#1e293b" strokeDasharray="3 3" />
                  <XAxis dataKey="grade" stroke="#64748b" fontSize={11} />
                  <YAxis stroke="#64748b" fontSize={11} />
                  <Tooltip contentStyle={{ background: '#0b1020', border: '1px solid #1e293b', borderRadius: 8, fontSize: 12 }} />
                  <Bar dataKey="count" fill="#a78bfa" radius={[6, 6, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </Card>

        <Card>
          <SectionTitle title="Top 10 teachers · lesson plans created" />
          <div className="h-72 px-2 pb-3">
            {topTeachers.length === 0 ? <EmptyState title="No teacher data" /> : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={topTeachers} layout="vertical" margin={{ left: 30, right: 12 }}>
                  <CartesianGrid stroke="#1e293b" strokeDasharray="3 3" horizontal={false} />
                  <XAxis type="number" stroke="#64748b" fontSize={11} />
                  <YAxis dataKey="teacherName" type="category" stroke="#94a3b8" fontSize={11} width={120} />
                  <Tooltip contentStyle={{ background: '#0b1020', border: '1px solid #1e293b', borderRadius: 8, fontSize: 12 }} />
                  <Bar dataKey="lessonPlanCount" fill="#22d3ee" radius={[0, 6, 6, 0]} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </Card>
      </div>

      <Card className="mt-5">
        <SectionTitle
          title="All lesson plans"
          hint={`${filtered.length} of ${plans.length}`}
          right={<div className="w-64"><SearchInput value={search} onChange={setSearch} placeholder="Search title, teacher, grade…" /></div>}
        />
        {filtered.length === 0 ? (
          <EmptyState title="No matches" />
        ) : (
          <div className="max-h-[600px] overflow-y-auto">
            <table className="w-full text-sm">
              <thead className="sticky top-0 bg-slate-900/95 backdrop-blur">
                <tr className="border-b border-slate-800/70 text-left text-[11px] uppercase tracking-wider text-slate-500">
                  <th className="px-5 py-3">Title</th>
                  <th className="px-4 py-3">Teacher</th>
                  <th className="px-4 py-3">Grade</th>
                  <th className="px-4 py-3">Subject</th>
                  <th className="px-4 py-3">Created</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((p) => (
                  <tr key={p.id} className="border-b border-slate-800/40">
                    <td className="px-5 py-3 text-slate-100">{p.title}</td>
                    <td className="px-4 py-3 text-slate-300">{p.teacher_name || '—'}</td>
                    <td className="px-4 py-3"><Badge tone="slate">{p.grade_level || '—'}</Badge></td>
                    <td className="px-4 py-3 text-slate-300">{p.subject || '—'}</td>
                    <td className="px-4 py-3 text-xs text-slate-400">{format(new Date(p.created_at), 'MMM d, yyyy')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </>
  );
};

export default MonitorLessonPlans;
