// src/services/imageStorage.ts
import { supabase } from "@/lib/supabase";
import { v4 as uuidv4 } from "uuid";

// ─── Image Storage Service ────────────────────────────────────────────────────────
// Handles storing generated images in Supabase Storage and recording them in the Database

const BUCKET_NAME = "generated-images";
const TABLE_NAME = "generated_images";

/** DB may store `userId/file.png`; uploads sometimes only have a full public URL in image_url. */
function normalizeStoragePath(raw: string | null | undefined): string | null {
  if (raw == null || String(raw).trim() === "") return null;
  const t = String(raw).trim();
  const publicMarker = `/object/public/${BUCKET_NAME}/`;
  const idx = t.indexOf(publicMarker);
  if (idx !== -1) return t.slice(idx + publicMarker.length).split("?")[0] ?? null;
  if (t.startsWith(`${BUCKET_NAME}/`)) return t.slice(BUCKET_NAME.length + 1);
  return t;
}

interface StoredImage {
  id: string;
  user_id: string;
  prompt: string;
  enhanced_prompt: string;
  aspect_ratio: string;
  style: string;
  image_url: string;
  storage_path: string;
  is_favorite: boolean;
  created_at: string;
}

export const imageStorage = {
  /**
   * Gets the number of images generated by the current user today
   */
  async getGenerationsCountToday(): Promise<number> {
    try {
      const user = (await supabase.auth.getUser()).data.user;
      if (!user) return 0;
      
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      
      const { count, error } = await supabase
        .from(TABLE_NAME)
        .select('*', { count: 'exact', head: true })
        .eq('user_id', user.id)
        .gte('created_at', today.toISOString());
        
      if (error) throw error;
      return count || 0;
    } catch (error) {
      console.error("Failed to get today's generation count:", error);
      return 0;
    }
  },

  /**
   * Uploads a base64 or blob image to Supabase Storage and creates a record in the database
   */
  async saveImage(
    base64Data: string, 
    metadata: {
      prompt: string;
      enhancedPrompt: string;
      aspectRatio: string;
      style: string;
    }
  ): Promise<StoredImage | null> {
    try {
      const user = (await supabase.auth.getUser()).data.user;
      if (!user) throw new Error("User not authenticated");

      // 1. Convert base64 to Blob
      const response = await fetch(base64Data);
      const blob = await response.blob();
      
      // 2. Upload to Storage
      const fileName = `${user.id}/${uuidv4()}.png`;
      const { data: uploadData, error: uploadError } = await supabase.storage
        .from(BUCKET_NAME)
        .upload(fileName, blob, {
          contentType: "image/png",
          upsert: false
        });

      if (uploadError) {
        console.error("Storage upload error:", uploadError);
        throw uploadError;
      }

      // 3. Get Public URL
      const { data: { publicUrl } } = supabase.storage
        .from(BUCKET_NAME)
        .getPublicUrl(fileName);

      // 4. Insert Record into Database
      const { data: insertData, error: insertError } = await supabase
        .from(TABLE_NAME)
        .insert({
          user_id: user.id,
          prompt: metadata.prompt,
          enhanced_prompt: metadata.enhancedPrompt,
          aspect_ratio: metadata.aspectRatio,
          style: metadata.style,
          image_url: publicUrl,
          storage_path: fileName,
          is_favorite: false
        })
        .select()
        .single();

      if (insertError) {
        // If DB insert fails, try to clean up the uploaded file
        await supabase.storage.from(BUCKET_NAME).remove([fileName]);
        console.error("Database insert error:", insertError);
        throw insertError;
      }

      return insertData as StoredImage;
    } catch (error) {
      console.error("Failed to save image:", error);
      return null;
    }
  },

  /**
   * Fetches all generated images for the current user
   */
  async getImages(): Promise<StoredImage[]> {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return [];

    const { data, error } = await supabase
      .from(TABLE_NAME)
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Failed to fetch images:", error);
      return [];
    }

    return data as StoredImage[];
  },

  /**
   * Deletes an image from both Storage and Database
   */
  async deleteImage(id: string, storagePath: string | null | undefined): Promise<boolean> {
    try {
      const user = (await supabase.auth.getUser()).data.user;
      if (!user) {
        console.error("deleteImage: not authenticated");
        return false;
      }

      const path = normalizeStoragePath(storagePath ?? undefined);

      // 1. Delete from Storage (best effort — RLS/owner quirks should not block DB row removal)
      if (path) {
        const { error: storageError } = await supabase.storage
          .from(BUCKET_NAME)
          .remove([path]);

        if (storageError) console.warn("Storage deletion warning:", storageError);
      }

      // 2. Delete DB row and confirm a row was removed (avoids silent no-op on wrong id / RLS)
      const { data: deleted, error: dbError } = await supabase
        .from(TABLE_NAME)
        .delete()
        .eq("id", id)
        .eq("user_id", user.id)
        .select("id");

      if (dbError) throw dbError;
      if (!deleted?.length) {
        console.warn("deleteImage: no row deleted for id", id);
        return false;
      }

      return true;
    } catch (error) {
      console.error("Failed to delete image:", error);
      return false;
    }
  },

  /**
   * Toggles the favorite status of an image
   */
  async toggleFavorite(id: string, isFavorite: boolean): Promise<boolean> {
    const { error } = await supabase
      .from(TABLE_NAME)
      .update({ is_favorite: isFavorite })
      .eq("id", id);

    if (error) {
      console.error("Failed to update favorite status:", error);
      return false;
    }
    return true;
  }
};
