/**
 * Student Management Service
 * All Supabase CRUD operations for students, assignments, submissions.
 *
 * Teacher operations use standard Supabase queries (RLS via auth.uid()).
 * Student (magic-link) operations use RPC functions with SECURITY DEFINER
 * to securely bypass RLS after verifying the student's access_token.
 */
import { supabase } from '@/lib/supabase';

// ── Types ──────────────────────────────────────────────

export interface Student {
  id: string;
  teacher_id: string;
  auth_user_id: string | null;
  access_token: string;
  student_code: string | null;
  account_status: 'active' | 'paused' | 'suspended';

  // Basic Information
  full_name: string;
  date_of_birth: string | null;
  gender: string | null;
  nationality: string | null;
  place_of_birth: string | null;
  home_language: string | null;

  // Contact & Guardian
  parent_name: string | null;
  parent_phone: string | null;
  parent_email: string | null;
  parent_relationship: string | null;
  home_address: string | null;

  // School Information
  school_name: string | null;
  grade_level: string;
  class_name: string | null;
  admission_number: string | null;
  academic_year: string | null;

  // Health & Needs
  blood_group: string | null;
  medical_conditions: string | null;
  allergies: string | null;
  special_needs: string | null;
  disability_status: string | null;

  // Additional
  previous_school: string | null;
  profile_photo_url: string | null;
  notes: string | null;

  created_at: string;
  updated_at: string;
}

export interface StudentAssignment {
  id: string;
  teacher_id: string;
  title: string;
  description: string | null;
  subject: string;
  grade_level: string;
  due_date: string;
  status: 'active' | 'draft' | 'closed';
  max_score: number | null;
  instructions: string | null;
  attachment_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface AssignmentSubmission {
  id: string;
  assignment_id: string;
  student_id: string;
  file_url: string | null;
  notes: string | null;
  score: number | null;
  status: 'submitted' | 'graded' | 'returned';
  teacher_feedback: string | null;
  submitted_at: string;
  graded_at: string | null;
  // AI auto-grading fields
  ai_score: number | null;
  ai_feedback: string | null;
  ai_graded_at: string | null;
}

// ── Token Generation ───────────────────────────────────

/** Generate a cryptographically random access token */
export const generateAccessToken = (): string => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return Array.from(array, (b) => chars[b % chars.length]).join('');
};

/** Build the magic access link for a student */
export const buildAccessLink = (token: string): string => {
  return `${window.location.origin}/student-access/${token}`;
};

// ── Student CRUD (Teacher operations) ──────────────────

export const createStudent = async (
  data: Omit<Student, 'id' | 'created_at' | 'updated_at' | 'auth_user_id' | 'access_token' | 'student_code' | 'account_status'> & { teacher_id: string }
): Promise<Student> => {
  const token = generateAccessToken();
  // student_code is auto-generated by the DB trigger (MOM-YYYY-XXXX)
  const { data: student, error } = await supabase
    .from('students')
    .insert({
      ...data,
      access_token: token,
      account_status: 'active',
    })
    .select()
    .single();

  if (error) { console.error('Error creating student:', error); throw error; }
  return student as Student;
};

export const getStudentsByTeacher = async (teacherId: string): Promise<Student[]> => {
  const { data, error } = await supabase
    .from('students')
    .select('*')
    .eq('teacher_id', teacherId)
    .order('created_at', { ascending: false });

  if (error) { console.error('Error fetching students:', error); return []; }
  return (data || []) as Student[];
};

export const getStudentById = async (id: string): Promise<Student | null> => {
  const { data, error } = await supabase
    .from('students')
    .select('*')
    .eq('id', id)
    .single();

  if (error) { console.error('Error fetching student:', error); return null; }
  return data as Student;
};

export const getStudentByToken = async (token: string): Promise<Student | null> => {
  // Try RPC first (works for anon), fall back to direct query (works for authenticated)
  const { data: rpcData, error: rpcError } = await supabase
    .rpc('get_student_by_token_secure', { p_access_token: token });

  if (!rpcError && rpcData && rpcData.length > 0) {
    return rpcData[0] as Student;
  }

  // Fallback: direct query (works if anon SELECT policy exists on students)
  const { data, error } = await supabase
    .from('students')
    .select('*')
    .eq('access_token', token)
    .single();

  if (error) { console.error('Error fetching student by token:', error); return null; }
  return data as Student;
};

export const getStudentByAuthUserId = async (authUserId: string): Promise<Student | null> => {
  const { data, error } = await supabase
    .from('students')
    .select('*')
    .eq('auth_user_id', authUserId)
    .single();

  if (error) return null;
  return data as Student;
};

export const updateStudent = async (id: string, updates: Partial<Student>): Promise<void> => {
  const { error } = await supabase
    .from('students')
    .update({ ...updates, updated_at: new Date().toISOString() })
    .eq('id', id);

  if (error) { console.error('Error updating student:', error); throw error; }
};

export const deleteStudent = async (id: string): Promise<void> => {
  // Delete related assignment links and submissions first to avoid FK issues
  const { error: subErr } = await supabase
    .from('assignment_submissions')
    .delete()
    .eq('student_id', id);
  if (subErr) console.error('Error deleting student submissions:', subErr);

  const { error: linkErr } = await supabase
    .from('assignment_students')
    .delete()
    .eq('student_id', id);
  if (linkErr) console.error('Error deleting student links:', linkErr);

  const { error } = await supabase
    .from('students')
    .delete()
    .eq('id', id);

  if (error) { console.error('Error deleting student:', error); throw error; }
};

export const toggleStudentStatus = async (id: string, newStatus: 'active' | 'paused' | 'suspended'): Promise<void> => {
  await updateStudent(id, { account_status: newStatus });
};

/** Regenerate access token for a student (e.g., if compromised) */
export const regenerateAccessToken = async (id: string): Promise<string> => {
  const newToken = generateAccessToken();
  await updateStudent(id, { access_token: newToken } as Partial<Student>);
  return newToken;
};

// ── Assignments CRUD (Teacher operations) ──────────────

export const createAssignment = async (
  data: Omit<StudentAssignment, 'id' | 'created_at' | 'updated_at'>,
  studentIds: string[]
): Promise<StudentAssignment> => {
  const { data: assignment, error } = await supabase
    .from('assignments')
    .insert({
      teacher_id: data.teacher_id,
      title: data.title,
      description: data.description,
      subject: data.subject,
      grade_level: data.grade_level,
      due_date: data.due_date,
      status: data.status,
      max_score: data.max_score,
      instructions: data.instructions,
      attachment_url: data.attachment_url,
    })
    .select()
    .single();

  if (error) { console.error('Error creating assignment:', error); throw error; }

  // Link assignment to students
  if (studentIds.length > 0) {
    const links = studentIds.map((sid) => ({
      assignment_id: (assignment as StudentAssignment).id,
      student_id: sid,
    }));
    const { error: linkError } = await supabase.from('assignment_students').insert(links);
    if (linkError) console.error('Error linking students to assignment:', linkError);
  }

  return assignment as StudentAssignment;
};

export const getAssignmentsByTeacher = async (teacherId: string): Promise<StudentAssignment[]> => {
  const { data, error } = await supabase
    .from('assignments')
    .select('*')
    .eq('teacher_id', teacherId)
    .order('due_date', { ascending: false });

  if (error) { console.error('Error fetching assignments:', error); return []; }
  return (data || []) as StudentAssignment[];
};

/** Update assignment-student links (replace all links for an assignment) */
export const updateAssignmentStudents = async (
  assignmentId: string,
  studentIds: string[]
): Promise<void> => {
  // Delete existing links
  const { error: delErr } = await supabase
    .from('assignment_students')
    .delete()
    .eq('assignment_id', assignmentId);
  if (delErr) console.error('Error deleting old assignment links:', delErr);

  // Insert new links
  if (studentIds.length > 0) {
    const links = studentIds.map((sid) => ({
      assignment_id: assignmentId,
      student_id: sid,
    }));
    const { error: insErr } = await supabase.from('assignment_students').insert(links);
    if (insErr) console.error('Error inserting assignment links:', insErr);
  }
};

/**
 * Get assignments for a student — tries RPC first (for magic-link students),
 * falls back to direct query (for authenticated students or if RPC not deployed).
 */
export const getAssignmentsForStudent = async (studentId: string): Promise<StudentAssignment[]> => {
  const session = getStudentSession();

  // Try RPC if we have a student session with access_token
  if (session?.access_token) {
    const { data: rpcData, error: rpcError } = await supabase
      .rpc('get_student_assignments_by_token', {
        p_student_id: studentId,
        p_access_token: session.access_token,
      });

    if (!rpcError && rpcData) {
      return rpcData as StudentAssignment[];
    }
    // If RPC fails (not deployed yet), fall through to direct query
    console.warn('RPC get_student_assignments_by_token failed, falling back to direct query:', rpcError?.message);
  }

  // Fallback: direct query (works with anon policies)
  const { data: links, error: linkError } = await supabase
    .from('assignment_students')
    .select('assignment_id')
    .eq('student_id', studentId);

  if (linkError || !links?.length) return [];

  const assignmentIds = links.map((l: any) => l.assignment_id);

  const { data, error } = await supabase
    .from('assignments')
    .select('*')
    .in('id', assignmentIds)
    .eq('status', 'active')
    .order('due_date', { ascending: true });

  if (error) { console.error('Error fetching student assignments:', error); return []; }
  return (data || []) as StudentAssignment[];
};

export const updateAssignment = async (id: string, updates: Partial<StudentAssignment>): Promise<void> => {
  const { error } = await supabase
    .from('assignments')
    .update({ ...updates, updated_at: new Date().toISOString() })
    .eq('id', id);

  if (error) { console.error('Error updating assignment:', error); throw error; }
};

export const deleteAssignment = async (id: string): Promise<void> => {
  // Delete related submissions and links first
  const { error: subErr } = await supabase
    .from('assignment_submissions')
    .delete()
    .eq('assignment_id', id);
  if (subErr) console.error('Error deleting assignment submissions:', subErr);

  const { error: linkErr } = await supabase
    .from('assignment_students')
    .delete()
    .eq('assignment_id', id);
  if (linkErr) console.error('Error deleting assignment links:', linkErr);

  const { error } = await supabase
    .from('assignments')
    .delete()
    .eq('id', id);

  if (error) { console.error('Error deleting assignment:', error); throw error; }
};

// Get student IDs linked to a specific assignment
export const getAssignmentStudents = async (assignmentId: string): Promise<string[]> => {
  const { data, error } = await supabase
    .from('assignment_students')
    .select('student_id')
    .eq('assignment_id', assignmentId);

  if (error) return [];
  return (data || []).map((d: any) => d.student_id);
};

// Get a single assignment by ID
export const getAssignmentById = async (id: string): Promise<StudentAssignment | null> => {
  const { data, error } = await supabase
    .from('assignments')
    .select('*')
    .eq('id', id)
    .single();

  if (error) { console.error('Error fetching assignment:', error); return null; }
  return data as StudentAssignment;
};

// ── File Upload ────────────────────────────────────────

/** Upload a student profile photo */
export const uploadProfilePhoto = async (
  file: File,
  studentId: string
): Promise<string> => {
  const ext = file.name.split('.').pop() || 'jpg';
  // Use a timestamp to prevent caching issues on updates
  const path = `profiles/${studentId}/avatar_${Date.now()}.${ext}`;

  // Try to use 'public-files' or fallback to 'assignment-files' if not available
  // For now we assume 'assignment-files' exists and is used for everything
  const { error } = await supabase.storage
    .from('assignment-files')
    .upload(path, file, { cacheControl: '3600', upsert: false });

  if (error) {
    console.error('Error uploading profile photo:', error);
    throw new Error('Failed to upload photo. Please try again.');
  }

  const { data: urlData } = supabase.storage
    .from('assignment-files')
    .getPublicUrl(path);

  return urlData.publicUrl;
};

/** Update student profile photo URL in database */
export const updateStudentProfilePhoto = async (
  studentId: string,
  photoUrl: string
): Promise<void> => {
  const { error } = await supabase
    .from('students')
    .update({ profile_photo_url: photoUrl })
    .eq('id', studentId);

  if (error) {
    console.error('Error updating profile photo url:', error);
    throw new Error('Failed to update profile.');
  }
};

/** Upload a file to Supabase Storage and return the public URL */
export const uploadSubmissionFile = async (
  file: File,
  studentId: string,
  assignmentId: string,
): Promise<string> => {
  const ext = file.name.split('.').pop() || 'file';
  const path = `submissions/${studentId}/${assignmentId}/${Date.now()}.${ext}`;

  const { error } = await supabase.storage
    .from('assignment-files')
    .upload(path, file, { cacheControl: '3600', upsert: false });

  if (error) {
    console.error('Error uploading file:', error);
    throw new Error('Failed to upload file. Please try again.');
  }

  const { data: urlData } = supabase.storage
    .from('assignment-files')
    .getPublicUrl(path);

  return urlData.publicUrl;
};

/**
 * Upload a teacher attachment file (for assignment materials)
 * Returns the public URL
 */
export const uploadAttachmentFile = async (
  file: File,
  teacherId: string,
): Promise<string> => {
  const ext = file.name.split('.').pop() || 'file';
  const safeName = file.name.replace(/[^a-zA-Z0-9.-]/g, '_');
  const path = `attachments/${teacherId}/${Date.now()}-${safeName}`;

  const { error } = await supabase.storage
    .from('assignment-files')
    .upload(path, file, { cacheControl: '3600', upsert: false });

  if (error) {
    console.error('Error uploading attachment:', error);
    throw new Error('Failed to upload attachment. Please try again.');
  }

  const { data: urlData } = supabase.storage
    .from('assignment-files')
    .getPublicUrl(path);

  return urlData.publicUrl;
};

/**
 * Get assignment statistics for a teacher's dashboard
 */
export interface AssignmentStats {
  totalAssignments: number;
  activeAssignments: number;
  draftAssignments: number;
  closedAssignments: number;
  totalStudentsAssigned: number;
  totalSubmissions: number;
  gradedSubmissions: number;
  pendingGrades: number;
  overdueAssignments: number;
}

export const getAssignmentStatsForTeacher = async (teacherId: string): Promise<AssignmentStats> => {
  try {
    // Get all assignments
    const { data: assignments } = await supabase
      .from('assignments')
      .select('id, status, due_date')
      .eq('teacher_id', teacherId);

    const allAssignments = assignments || [];
    const now = new Date();

    // Get assignment-student links
    const assignmentIds = allAssignments.map(a => a.id);
    const { data: links } = await supabase
      .from('assignment_students')
      .select('assignment_id, student_id')
      .in('assignment_id', assignmentIds);

    // Get submissions
    const { data: submissions } = await supabase
      .from('assignment_submissions')
      .select('id, status')
      .in('assignment_id', assignmentIds);

    const allLinks = links || [];
    const allSubmissions = submissions || [];

    return {
      totalAssignments: allAssignments.length,
      activeAssignments: allAssignments.filter(a => a.status === 'active').length,
      draftAssignments: allAssignments.filter(a => a.status === 'draft').length,
      closedAssignments: allAssignments.filter(a => a.status === 'closed').length,
      totalStudentsAssigned: allLinks.length,
      totalSubmissions: allSubmissions.length,
      gradedSubmissions: allSubmissions.filter(s => s.status === 'graded' || s.status === 'returned').length,
      pendingGrades: allSubmissions.filter(s => s.status === 'submitted').length,
      overdueAssignments: allAssignments.filter(a => 
        a.status === 'active' && new Date(a.due_date) < now
      ).length,
    };
  } catch (err) {
    console.error('Error getting assignment stats:', err);
    return {
      totalAssignments: 0,
      activeAssignments: 0,
      draftAssignments: 0,
      closedAssignments: 0,
      totalStudentsAssigned: 0,
      totalSubmissions: 0,
      gradedSubmissions: 0,
      pendingGrades: 0,
      overdueAssignments: 0,
    };
  }
};

/**
 * Get student submission statistics
 */
export interface StudentStats {
  totalAssigned: number;
  submitted: number;
  pending: number;
  graded: number;
  averageScore: number | null;
  latestSubmission: string | null;
}

export const getStudentStats = async (studentId: string): Promise<StudentStats> => {
  try {
    // Get assignments assigned to this student
    const { data: links } = await supabase
      .from('assignment_students')
      .select('assignment_id')
      .eq('student_id', studentId);

    const assignmentIds = (links || []).map((l: any) => l.assignment_id);

    // Get student's submissions
    const { data: submissions } = await supabase
      .from('assignment_submissions')
      .select('*')
      .eq('student_id', studentId)
      .order('submitted_at', { ascending: false });

    const allSubmissions = (submissions || []) as AssignmentSubmission[];
    const gradedOnes = allSubmissions.filter(s => 
      (s.status === 'graded' || s.status === 'returned') && s.score !== null
    );

    const avgScore = gradedOnes.length > 0
      ? gradedOnes.reduce((sum, s) => sum + (s.score || 0), 0) / gradedOnes.length
      : null;

    return {
      totalAssigned: assignmentIds.length,
      submitted: allSubmissions.length,
      pending: assignmentIds.length - allSubmissions.length,
      graded: gradedOnes.length,
      averageScore: avgScore ? Math.round(avgScore * 10) / 10 : null,
      latestSubmission: allSubmissions[0]?.submitted_at || null,
    };
  } catch (err) {
    console.error('Error getting student stats:', err);
    return {
      totalAssigned: 0,
      submitted: 0,
      pending: 0,
      graded: 0,
      averageScore: null,
      latestSubmission: null,
    };
  }
};

// ── Submissions CRUD ───────────────────────────────────

/**
 * Submit an assignment — tries RPC first (for magic-link students),
 * falls back to direct insert.
 */
export const submitAssignment = async (
  data: { assignment_id: string; student_id: string; file_url?: string; notes?: string }
): Promise<AssignmentSubmission> => {
  const session = getStudentSession();

  // Try RPC for magic-link students
  if (session?.access_token) {
    const { data: rpcData, error: rpcError } = await supabase
      .rpc('submit_assignment_by_token', {
        p_student_id: data.student_id,
        p_access_token: session.access_token,
        p_assignment_id: data.assignment_id,
        p_notes: data.notes || null,
        p_file_url: data.file_url || null,
      });

    if (!rpcError && rpcData) {
      // RPC returns a single row or array depending on Supabase version
      const submission = Array.isArray(rpcData) ? rpcData[0] : rpcData;
      return submission as AssignmentSubmission;
    }
    console.warn('RPC submit_assignment_by_token failed, falling back to direct insert:', rpcError?.message);
  }

  // Fallback: direct insert (works with anon INSERT policy)
  const { data: submission, error } = await supabase
    .from('assignment_submissions')
    .insert({
      assignment_id: data.assignment_id,
      student_id: data.student_id,
      file_url: data.file_url || null,
      notes: data.notes || null,
      status: 'submitted',
    })
    .select()
    .single();

  if (error) { console.error('Error submitting assignment:', error); throw error; }
  return submission as AssignmentSubmission;
};

export const getSubmissionsForAssignment = async (assignmentId: string): Promise<AssignmentSubmission[]> => {
  const { data, error } = await supabase
    .from('assignment_submissions')
    .select('*')
    .eq('assignment_id', assignmentId)
    .order('submitted_at', { ascending: false });

  if (error) return [];
  return (data || []) as AssignmentSubmission[];
};

/**
 * Get submissions for a student — tries RPC first (for magic-link students),
 * falls back to direct query.
 */
export const getSubmissionsForStudent = async (studentId: string): Promise<AssignmentSubmission[]> => {
  const session = getStudentSession();

  // Try RPC for magic-link students
  if (session?.access_token) {
    const { data: rpcData, error: rpcError } = await supabase
      .rpc('get_student_submissions_by_token', {
        p_student_id: studentId,
        p_access_token: session.access_token,
      });

    if (!rpcError && rpcData) {
      return rpcData as AssignmentSubmission[];
    }
    console.warn('RPC get_student_submissions_by_token failed, falling back to direct query:', rpcError?.message);
  }

  // Fallback: direct query (works with anon SELECT policy)
  const { data, error } = await supabase
    .from('assignment_submissions')
    .select('*')
    .eq('student_id', studentId)
    .order('submitted_at', { ascending: false });

  if (error) return [];
  return (data || []) as AssignmentSubmission[];
};

export const gradeSubmission = async (
  submissionId: string,
  score: number,
  feedback: string
): Promise<void> => {
  const { error } = await supabase
    .from('assignment_submissions')
    .update({
      score,
      teacher_feedback: feedback,
      status: 'graded',
      graded_at: new Date().toISOString(),
    })
    .eq('id', submissionId);

  if (error) { console.error('Error grading submission:', error); throw error; }
};

/** Return a graded submission back to the student (sets status to 'returned') */
export const returnSubmission = async (
  submissionId: string,
  score: number | null,
  feedback: string
): Promise<void> => {
  const { error } = await supabase
    .from('assignment_submissions')
    .update({
      score,
      teacher_feedback: feedback,
      status: 'returned',
      graded_at: new Date().toISOString(),
    })
    .eq('id', submissionId);

  if (error) { console.error('Error returning submission:', error); throw error; }
};

/**
 * Get students who haven't submitted an assignment yet
 */
export const getUnsubmittedStudents = async (
  assignmentId: string,
  students: Student[]
): Promise<Student[]> => {
  const studentIds = students.map(s => s.id);
  
  // Get assigned students
  const { data: links } = await supabase
    .from('assignment_students')
    .select('student_id')
    .eq('assignment_id', assignmentId)
    .in('student_id', studentIds);

  const assignedIds = new Set((links || []).map((l: any) => l.student_id));

  // Get students who have submitted
  const { data: submissions } = await supabase
    .from('assignment_submissions')
    .select('student_id')
    .eq('assignment_id', assignmentId);

  const submittedIds = new Set((submissions || []).map((s: any) => s.student_id));

  // Return students who are assigned but haven't submitted
  return students.filter(s => assignedIds.has(s.id) && !submittedIds.has(s.id));
};

/**
 * Get a breakdown of submission status for an assignment
 */
export interface SubmissionBreakdown {
  assigned: number;
  submitted: number;
  pending: number;
  graded: number;
  aiReviewed: number;
  late: number;
}

export const getSubmissionBreakdown = async (
  assignmentId: string,
  dueDate: Date
): Promise<SubmissionBreakdown> => {
  // Count assigned students
  const { count: assignedCount } = await supabase
    .from('assignment_students')
    .select('*', { count: 'exact', head: true })
    .eq('assignment_id', assignmentId);

  // Get submissions
  const { data: submissions } = await supabase
    .from('assignment_submissions')
    .select('status, submitted_at, ai_graded_at')
    .eq('assignment_id', assignmentId);

  const subs = submissions || [];
  
  return {
    assigned: assignedCount || 0,
    submitted: subs.length,
    pending: (assignedCount || 0) - subs.length,
    graded: subs.filter(s => s.status === 'graded' || s.status === 'returned').length,
    aiReviewed: subs.filter(s => s.ai_graded_at).length,
    late: subs.filter(s => new Date(s.submitted_at) > dueDate).length,
  };
};

/** Get all submissions for assignments belonging to a teacher, enriched with student names */
export const getSubmissionsForTeacher = async (teacherId: string): Promise<
  (AssignmentSubmission & { student_name?: string; assignment_title?: string })[]
> => {
  // Get teacher's assignment IDs
  const { data: assignments, error: aErr } = await supabase
    .from('assignments')
    .select('id, title')
    .eq('teacher_id', teacherId);

  if (aErr || !assignments?.length) return [];

  const assignmentIds = assignments.map((a: any) => a.id);
  const assignmentMap = Object.fromEntries(assignments.map((a: any) => [a.id, a.title]));

  // Get all submissions for those assignments
  const { data: subs, error: sErr } = await supabase
    .from('assignment_submissions')
    .select('*')
    .in('assignment_id', assignmentIds)
    .order('submitted_at', { ascending: false });

  if (sErr || !subs?.length) return [];

  // Get student names
  const studentIds = [...new Set(subs.map((s: any) => s.student_id))];
  const { data: students } = await supabase
    .from('students')
    .select('id, full_name')
    .in('id', studentIds);

  const studentMap = Object.fromEntries((students || []).map((s: any) => [s.id, s.full_name]));

  return subs.map((s: any) => ({
    ...s,
    student_name: studentMap[s.student_id] || 'Unknown Student',
    assignment_title: assignmentMap[s.assignment_id] || 'Unknown Assignment',
  }));
};

// ── Student Session (for magic-link access) ────────────

const STUDENT_SESSION_KEY = 'mom_student_session';

/** Persist student record to localStorage after magic-link validation */
export const setStudentSession = (student: Student): void => {
  localStorage.setItem(STUDENT_SESSION_KEY, JSON.stringify(student));
};

/** Retrieve the current student session (if any) */
export const getStudentSession = (): Student | null => {
  try {
    const raw = localStorage.getItem(STUDENT_SESSION_KEY);
    if (!raw) return null;
    const student = JSON.parse(raw) as Student;
    // Validate session has required fields
    if (!student.id || !student.access_token || !student.full_name) {
      clearStudentSession();
      return null;
    }
    return student;
  } catch {
    clearStudentSession();
    return null;
  }
};

/** Clear the student session (sign out) */
export const clearStudentSession = (): void => {
  localStorage.removeItem(STUDENT_SESSION_KEY);
};

/** Refresh the student session from the database */
export const refreshStudentSession = async (): Promise<Student | null> => {
  const current = getStudentSession();
  if (!current) return null;

  // Use token-based lookup (works for anon/magic-link)
  const fresh = await getStudentByToken(current.access_token);
  if (fresh && fresh.account_status !== 'suspended') {
    setStudentSession(fresh);
    return fresh;
  }

  // Student was suspended or token invalidated
  clearStudentSession();
  return null;
};

/** Check if the student session is still valid (account is active) */
export const isStudentSessionValid = (): boolean => {
  const session = getStudentSession();
  if (!session) return false;
  return session.account_status === 'active';
};
