/**
 * Text helpers for the partner monitor.
 *
 * The AI generated by OpenRouter, by the chatbot, and by the homework
 * uploader frequently includes Markdown formatting (** bold **, ## headings,
 * `code`, bullet `-` markers, etc.). The monitor renders that text as
 * plain paragraphs in `<div whitespace-pre-wrap>` blocks, so the markers
 * appear as literal characters which looks like raw, dirty data to a
 * non-technical partner.
 *
 * `stripMarkdown` removes the most common markers without disturbing the
 * underlying content.
 */
export const stripMarkdown = (text?: string | null): string => {
  if (!text) return '';
  return text
    // fenced code blocks → keep inner text only
    .replace(/```[a-zA-Z0-9_-]*\n([\s\S]*?)```/g, '$1')
    // inline code `x` → x
    .replace(/`([^`]+)`/g, '$1')
    // ATX headings: "## Title" → "Title"
    .replace(/^\s{0,3}#{1,6}\s+/gm, '')
    // bold + italic combinations
    .replace(/\*\*\*(.+?)\*\*\*/g, '$1')
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/__(.+?)__/g, '$1')
    // single-asterisk italics  *like this*  → like this
    .replace(/(^|[^\w*])\*(?!\s)([^*\n]+?)\*(?!\w)/g, '$1$2')
    // single-underscore italics  _like this_
    .replace(/(^|[^\w_])_(?!\s)([^_\n]+?)_(?!\w)/g, '$1$2')
    // strikethrough
    .replace(/~~(.+?)~~/g, '$1')
    // markdown links  [text](url) → text
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1')
    // bullet markers ("- " / "* " / "+ ") → "• "
    .replace(/^\s*[-*+]\s+/gm, '• ')
    // numbered list "1. " markers → drop number, keep text
    .replace(/^\s*\d+\.\s+/gm, '')
    // blockquote markers
    .replace(/^>\s?/gm, '')
    // horizontal rules
    .replace(/^\s*[-*_]{3,}\s*$/gm, '')
    // collapse 3+ newlines to 2
    .replace(/\n{3,}/g, '\n\n')
    .trim();
};
