import { useState, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { getAllLessonPlans } from "@/services/adminService";
import type { LessonPlanStats } from "@/types/admin";
import {
  Search,
  BookOpen,
  Users,
  Calendar,
  Download,
} from "lucide-react";
import { motion } from "framer-motion";
import { format } from "date-fns";

const LessonPlansManagement = () => {
  const [lessonPlans, setLessonPlans] = useState<LessonPlanStats[]>([]);
  const [filteredPlans, setFilteredPlans] = useState<LessonPlanStats[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      setLoading(true);
      const data = await getAllLessonPlans();
      setLessonPlans(data);
      setFilteredPlans(data);
      setLoading(false);
    };
    fetchData();
  }, []);

  useEffect(() => {
    if (searchQuery.trim() === "") {
      setFilteredPlans(lessonPlans);
    } else {
      const query = searchQuery.toLowerCase();
      setFilteredPlans(
        lessonPlans.filter(
          (p) =>
            p.title.toLowerCase().includes(query) ||
            p.grade_level.toLowerCase().includes(query) ||
            p.subject.toLowerCase().includes(query) ||
            p.teacher_name?.toLowerCase().includes(query) ||
            p.topic?.toLowerCase().includes(query)
        )
      );
    }
  }, [searchQuery, lessonPlans]);

  const exportToCSV = () => {
    const headers = ['Title', 'Grade', 'Subject', 'Topic', 'Teacher', 'Created'];
    const csvData = filteredPlans.map(p => [
      p.title.replace(/,/g, ';'),
      p.grade_level,
      p.subject,
      p.topic?.replace(/,/g, ';') || '',
      p.teacher_name || '',
      p.created_at ? format(new Date(p.created_at), 'yyyy-MM-dd') : '',
    ]);
    
    const csv = [headers.join(','), ...csvData.map(row => row.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `lesson-plans-export-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    a.click();
  };

  // Group by grade for stats
  const gradeStats = lessonPlans.reduce((acc, p) => {
    acc[p.grade_level] = (acc[p.grade_level] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  // Group by teacher
  const teacherStats = lessonPlans.reduce((acc, p) => {
    const name = p.teacher_name || 'Unknown';
    acc[name] = (acc[name] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
          className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full"
        />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white">Lesson Plans</h1>
          <p className="text-gray-400 mt-1">
            {lessonPlans.length} lesson plans generated by teachers
          </p>
        </div>
        <Button 
          onClick={exportToCSV}
          className="bg-indigo-600 hover:bg-indigo-700"
        >
          <Download className="w-4 h-4 mr-2" />
          Export CSV
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card className="bg-gray-900/50 border-gray-800">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-purple-500/10">
                <BookOpen className="w-5 h-5 text-purple-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-white">{lessonPlans.length}</p>
                <p className="text-xs text-gray-400">Total Plans</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-gray-900/50 border-gray-800">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-blue-500/10">
                <Users className="w-5 h-5 text-blue-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-white">
                  {Object.keys(teacherStats).length}
                </p>
                <p className="text-xs text-gray-400">Teachers</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-gray-900/50 border-gray-800">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-emerald-500/10">
                <Calendar className="w-5 h-5 text-emerald-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-white">
                  {Object.keys(gradeStats).length}
                </p>
                <p className="text-xs text-gray-400">Grade Levels</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="bg-gray-900/50 border-gray-800">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-lg bg-amber-500/10">
                <BookOpen className="w-5 h-5 text-amber-400" />
              </div>
              <div>
                <p className="text-2xl font-bold text-white">
                  {lessonPlans.length > 0 && Object.keys(teacherStats).length > 0
                    ? (lessonPlans.length / Object.keys(teacherStats).length).toFixed(1)
                    : 0}
                </p>
                <p className="text-xs text-gray-400">Avg per Teacher</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Grade Distribution */}
      <Card className="bg-gray-900/50 border-gray-800">
        <CardContent className="p-4">
          <h3 className="text-sm font-medium text-gray-400 mb-3">Plans by Grade Level</h3>
          <div className="flex flex-wrap gap-2">
            {Object.entries(gradeStats).sort((a, b) => a[0].localeCompare(b[0])).map(([grade, count]) => (
              <Badge key={grade} variant="outline" className="bg-gray-800/50 border-gray-700 text-white">
                {grade}: <span className="ml-1 text-purple-400">{count}</span>
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Search */}
      <Card className="bg-gray-900/50 border-gray-800">
        <CardContent className="p-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              placeholder="Search by title, topic, grade, subject, or teacher..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 bg-gray-800/50 border-gray-700 text-white placeholder:text-gray-500"
            />
          </div>
        </CardContent>
      </Card>

      {/* Lesson Plans Table */}
      <Card className="bg-gray-900/50 border-gray-800 overflow-hidden">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow className="border-gray-800 hover:bg-transparent">
                  <TableHead className="text-gray-400">Title</TableHead>
                  <TableHead className="text-gray-400">Topic</TableHead>
                  <TableHead className="text-gray-400">Grade</TableHead>
                  <TableHead className="text-gray-400">Subject</TableHead>
                  <TableHead className="text-gray-400">Teacher</TableHead>
                  <TableHead className="text-gray-400">Created</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredPlans.map((plan, index) => (
                  <motion.tr
                    key={plan.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.02 }}
                    className="border-gray-800 hover:bg-gray-800/50"
                  >
                    <TableCell>
                      <p className="font-medium text-white max-w-xs truncate">
                        {plan.title}
                      </p>
                    </TableCell>
                    <TableCell className="text-gray-300 max-w-xs truncate">
                      {plan.topic || '-'}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className="bg-purple-500/10 border-purple-500/30 text-purple-400">
                        {plan.grade_level}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-gray-300">
                      {plan.subject}
                    </TableCell>
                    <TableCell className="text-gray-300">
                      {plan.teacher_name || '-'}
                    </TableCell>
                    <TableCell className="text-gray-400 text-sm">
                      {plan.created_at
                        ? format(new Date(plan.created_at), 'MMM d, yyyy')
                        : '-'}
                    </TableCell>
                  </motion.tr>
                ))}
              </TableBody>
            </Table>
          </div>
          {filteredPlans.length === 0 && (
            <div className="text-center py-12">
              <p className="text-gray-400">No lesson plans found</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default LessonPlansManagement;
